# SPDX-License-Identifier: GPL-2.0-only

ifeq ($(LASSEN_ROOT),)
LASSEN_ROOT=$(srctree)/../transceiver-driver/drivers
endif

obj-m += fpc_qsfp.o
fpc_qsfp-y += fpc.o qsfp.o sff8636.o sff8472.o transceiver_debugfs.o \
              fpc_led.o cmis.o sff8636_debugfs.o cmis_debugfs.o trx_sysfs.o

ccflags-y := -I$(KERNEL_SRC)/include
ccflags-y += -I$(KERNEL_SRC)/drivers/net/phy
ccflags-y += -I$(LASSEN_ROOT)/include
